services:
    app:
        image: "nginx:stable-alpine"
        container_name: "{{ app_name }}"
        restart: unless-stopped
        ports:
            - "${PANEL_APP_PORT_HTTP}:80/tcp"
        volumes:
            - "./conf/nginx.conf:/etc/nginx/nginx.conf:ro"
            - "./conf/sites-available:/etc/nginx/sites-available:ro"
            - "./conf/sites-enabled:/etc/nginx/sites-enabled:ro"
            - "./conf/includes:/etc/nginx/includes:ro"
            - "./log:/var/log/nginx"
            - "/opt/mana-panel/www:/opt/mana-panel/www:ro"
