services:
    app:
        image: "caddy:2-alpine"
        container_name: "{{ app_name }}"
        restart: unless-stopped
        ports:
            - "${PANEL_APP_PORT_HTTP}:80/tcp"
            - "${PANEL_APP_PORT_HTTPS}:443/tcp"
        volumes:
            - "./conf/Caddyfile:/etc/caddy/Caddyfile:ro"
            - "./conf/sites:/etc/caddy/sites:ro"
            - "./data:/data"
            - "./config:/config"
            - "/opt/mana-panel/www:/opt/mana-panel/www:ro"
        command:
            - "caddy"
            - "run"
            - "--config"
            - "/etc/caddy/Caddyfile"
            - "--adapter"
            - "caddyfile"
